//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Form115Entities : DbContext
    {
        public Form115Entities()
            : base("name=Form115Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hotels> Hotels { get; set; }
        public virtual DbSet<Produits> Produits { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Sejours> Sejours { get; set; }
        public virtual DbSet<Utilisateurs> Utilisateurs { get; set; }
    }
}
