//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pays
    {
        public Pays()
        {
            this.Villes = new HashSet<Villes>();
        }
    
        public string CodeIso3 { get; set; }
        public string Name { get; set; }
        public double surfacearea { get; set; }
        public Nullable<short> indepyear { get; set; }
        public int population { get; set; }
        public Nullable<double> lifeexpectancy { get; set; }
        public Nullable<double> gnp { get; set; }
        public Nullable<double> gnpold { get; set; }
        public string localName { get; set; }
        public string CodeIso2 { get; set; }
        public int idRegion { get; set; }
        public int idgovform { get; set; }
        public Nullable<int> idheadofstate { get; set; }
    
        public virtual Regions Regions { get; set; }
        public virtual ICollection<Villes> Villes { get; set; }
    }
}
