//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Villes
    {
        public Villes()
        {
            this.Hotels = new HashSet<Hotels>();
        }
    
        public int idVille { get; set; }
        public string name { get; set; }
        public string CodeIso3 { get; set; }
        public string district { get; set; }
        public int population { get; set; }
        public short isCapital { get; set; }
    
        public virtual ICollection<Hotels> Hotels { get; set; }
        public virtual Pays Pays { get; set; }
    }
}
